# Generated by Django 5.0.6 on 2024-06-26 07:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NepalDistrict',
            fields=[
                ('ddgn', models.AutoField(db_column='DDGN', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('ddgn_0', models.BigIntegerField(blank=True, db_column='ddgn', null=True)),
                ('first_dcod', models.BigIntegerField(blank=True, null=True)),
                ('first_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('first_gn_c', models.FloatField(blank=True, null=True)),
                ('first_stat', models.BigIntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('centroid_x', models.FloatField(blank=True, null=True)),
                ('centroid_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nepal_district',
                'managed': False,
            },
        ),
    ]
